name: Test MacOS
on:
  workflow_call:
    inputs:
      distro-slug:
        type: string
        required: true
        description: The Distribution Slug

      display-name:
        type: string
        required: true
        description: The Display Name For The Job

      runs-on:
        type: string
        required: true
        description: The GitHub MacOS Worker To Run Workflow On

      instances:
        type: string
        required: true
        description: The Instances To Test

      timeout:
        type: number
        required: false
        default: 20
        description: The timeout(in minutes) for the workflow

## DGM env:
## DGM   KITCHEN_LOCAL_YAML: 'kitchen.macos.yml'
## DGM
## DGM Wonder what the KITCHEN_LOCAL_YAML had to be set here for MacOS, do we need to do something similar for runners ?

jobs:
  Test:
    name: ${{ matrix.instance }}
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout }}
    strategy:
      fail-fast: false
      matrix:
        instance: ${{ fromJSON(inputs.instances) }}

    steps:
      - uses: actions/checkout@v3

      ## DGM Need to replace this
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python Dependencies
        run: |
          pip install -U pip
          pip install -r tests/requirements.txt

      - name: Create Test Instance
        run: |
          ## DGM bundle exec kitchen create ${{ matrix.instance }}-${{ inputs.distro-slug }} || \
          ## DGM   (sleep 10 && bundle exec kitchen create ${{ matrix.instance }}-${{ inputs.distro-slug }})
          ## DGM
          ## DGM Need to select a GitHub runner here , macos-latest
          sleep 2

      - name: Test Bootstrap
        run: |
          ## DGM bundle exec kitchen verify ${{ matrix.instance }}-${{ inputs.distro-slug }}
          ## DGM
          ## DGM Need to run the bootstrap tests for MacOS here
          sleep 2

      - name: Destroy Test Instance
        if: always()
        run: |
          ## DGM bundle exec kitchen destroy ${{ matrix.instance }}-${{ inputs.distro-slug }}
          ## DGM
          ## DGM this can be removed since using GitHub shared runners, and it should just close when done with it
          sleep 2

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-${{ matrix.instance }}-${{ inputs.distro-slug }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
